
meta_product_name: "HolyTrip"
meta_title: "HolyTrip | Plan and Organize Your Next Trip"
meta_description: "Your personal trip planner for traveling with friends that helps you plan a trip, organize the details and keep everyone up-to-date from start to finish."
meta_image: "homepage.png"
# twitter_account: "@product_twitter_account"
