
meta_product_name: "HolyTrip"
meta_title: "HolyTrip | Plan and Organize Your Next Trip"
meta_description: "HolyTrip is your all-in-one personal, shared trip planner where you can organize your to do list, invite your friends and share the responsibilities."
meta_image: "homepage.png"
# twitter_account: "@product_twitter_account"
